### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by maciejmiara** [welpdev/mailchimp-bundle#1]
Symfony 3 is now widely used, it would be nice to support it.

**Comment by Nightbr** [comment]
Yep it is in the ToDo list ;) But if you want to look at it feel free to make a PR

Thanks

**Comment by maciejmiara** [comment]
I already did that.

In PR I also mentioned composer.lock.

**Comment by Nightbr** [comment]
Release done 1.0.5 available through composer.
Let me know if you have any issues with it!

**Comment by Nightbr** [comment]
I will close this issue, feel free to reopen it if you have any trouble with the Symfony 3 integration.
