### ISSUE TITLE
I want to add "tags" with subscribed user. There is no function in ListRepository

### ISSUE THREAD

**Issue by femina-clarion** [welpdev/mailchimp-bundle#24]
There should be function which will call mailchimp api
**/lists/{LISTID}/members/{EMAILHASH}/tags**

Is there any way to achieve this add tag functionality using your bundle?

**Comment by Nightbr** [comment]
You can use the service to make any request to MailChimp:
https://welpdev.github.io/mailchimp-bundle/usage/#retrieve-mailchimp-object-to-make-custom-mailchimp-api-v3-requests
