### ISSUE TITLE
Use EventDispatcher with closure factories

### ISSUE THREAD

**Issue by hirnlego** [welpdev/mailchimp-bundle#34]
As per Symfony >= 3.3 ContainerAwareEventDispatcher is deprecated and it seems that doing `$this->container->get('event_dispatcher')` is no longer valid.

**Comment by hirnlego** [comment]
Actually it could be a PhpStorm related issue:

https://github.com/symfony/symfony/issues/22402#issuecomment-321027236

**Comment by Nightbr** [comment]
Hey, thanks for your feedback, feel free to open a PR if you have a fix for this. I'm not using actively this bundle (no more using mailchimp in my projects) so feel free to fork and push some PR, I will gladly review, merge them & make a new release!

**Comment by hirnlego** [comment]
I'm not sure it's a bundle issue, I think we can ignore it at the moment. :)
