### ISSUE TITLE
Don't work with Symfony 5

### ISSUE THREAD

**Issue by iatanasov77** [welpdev/mailchimp-bundle#37]
This is the error:
`Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /projects/VankoSoft.org/vendor/welp/mailchimp-bundle/src/DependencyInjection/Configuration.php on line 20 and at least 1 expected`

I will fix the symfony version requirement. Pull Rquest: #38

**Comment by Nightbr** [comment]
Fixed in [`1.3.2`](https://github.com/welpdev/mailchimp-bundle/releases/tag/1.3.2)
